name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      #      - name: Install dependencies
      #        run: |
      #          cd assets
      #          npm install

      #      - name: Build
      #        run: |
      #          cd assets
      #          npm run build

      - name: Sync
        env:
          dest: "${{ secrets.SSH_USER }}@${{ secrets.IP }}:/var/www/dentist-theme.sarahjobs.com/wp-content/themes/dentist-theme"
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /assets/node_modules/ \
            ./ ${{env.dest}}
