name: Check Coding Standards

on: push

- "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install

    - name: Run Config
      run: composer cstd

    - name: Run CBF
      run: composer cbf

    - name: Run CS
      run: composer cs