name: PHPCS

on:
  pull_request:
    paths:
      - "**.php"

jobs:
  build:
    name: Check WPCS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install

      - name: Set WordPress Coding Standards path
        run: composer cstd

      - name: Run phpcs command
        run: composer cs

      - name: Save PHPCS Report
        uses: actions/upload-artifact@v2
        with:
          name: phpcs-report
          path: phpcs-reports
