name: Check Coding Standards

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run CS
      run: ./vendor/bin/phpcs --standard=.phpcs.xml .